# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: sum_app
    spec:
      containers:
        - name: sum_app
          image: dockerhub/sum_app:1.0
          ports:
            - containerPort: 5000

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
