# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: py_app
          image: dockerhub/pyapp:1.0
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "100m"
              memory: "100m"
      imagePullSecrets:
        - name: {{ .Values.registrysecretname }}
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: py-service
spec:
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registrysecretname }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
        {{ .Values.registrycredconfig }}